

services:
  vaani-app:
    build: .
    container_name: vaani-app
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "1935:1935"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
